// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 26.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'cart_geek';

  static const String assets_fonts_alegreyasans_black_ttf =
      'assets/fonts/AlegreyaSans-Black.ttf';

  static const String assets_fonts_alegreyasans_blackitalic_ttf =
      'assets/fonts/AlegreyaSans-BlackItalic.ttf';

  static const String assets_fonts_alegreyasans_bold_ttf =
      'assets/fonts/AlegreyaSans-Bold.ttf';

  static const String assets_fonts_alegreyasans_bolditalic_ttf =
      'assets/fonts/AlegreyaSans-BoldItalic.ttf';

  static const String assets_fonts_alegreyasans_extrabold_ttf =
      'assets/fonts/AlegreyaSans-ExtraBold.ttf';

  static const String assets_fonts_alegreyasans_extrabolditalic_ttf =
      'assets/fonts/AlegreyaSans-ExtraBoldItalic.ttf';

  static const String assets_fonts_alegreyasans_italic_ttf =
      'assets/fonts/AlegreyaSans-Italic.ttf';

  static const String assets_fonts_alegreyasans_light_ttf =
      'assets/fonts/AlegreyaSans-Light.ttf';

  static const String assets_fonts_alegreyasans_lightitalic_ttf =
      'assets/fonts/AlegreyaSans-LightItalic.ttf';

  static const String assets_fonts_alegreyasans_medium_ttf =
      'assets/fonts/AlegreyaSans-Medium.ttf';

  static const String assets_fonts_alegreyasans_mediumitalic_ttf =
      'assets/fonts/AlegreyaSans-MediumItalic.ttf';

  static const String assets_fonts_alegreyasans_regular_ttf =
      'assets/fonts/AlegreyaSans-Regular.ttf';

  static const String assets_fonts_alegreyasans_thin_ttf =
      'assets/fonts/AlegreyaSans-Thin.ttf';

  static const String assets_fonts_alegreyasans_thinitalic_ttf =
      'assets/fonts/AlegreyaSans-ThinItalic.ttf';

  static const String assets_fonts_ofl_txt = 'assets/fonts/OFL.txt';

  static const String assets_pngs_new_card_image_png =
      'assets/pngs/new_card_image.png';

  static const String assets_pngs_profile_pic_png =
      'assets/pngs/profile_pic.png';

  static const String assets_svgs_big_calendar_svg =
      'assets/svgs/big_calendar.svg';

  static const String assets_svgs_booking_icon_svg =
      'assets/svgs/booking_icon.svg';

  static const String assets_svgs_calendar_icon_svg =
      'assets/svgs/calendar_icon.svg';

  static const String assets_svgs_clock_icon_svg = 'assets/svgs/clock_icon.svg';

  static const String assets_svgs_drawer_icon_svg =
      'assets/svgs/drawer_icon.svg';

  static const String assets_svgs_home_icon_svg = 'assets/svgs/home_icon.svg';

  static const String assets_svgs_packages_icon_svg =
      'assets/svgs/packages_icon.svg';

  static const String assets_svgs_profile_icon_svg =
      'assets/svgs/profile_icon.svg';

  static const String assets_svgs_radio_icon_svg = 'assets/svgs/radio_icon.svg';
}
